export default FormatSystems = {
  Default: {
    any: "%.4g",
    "%": "%.3g",
    "kg/h": "%.0f",
    "Nm3/h(air)": "%.0f",
    "t/d": "%.5f",
    "t/a": "%.0f",
    "lb/h": "%.0f",
    "Nm3/h": "%.0f",
    SCFM60: "%.0f",
    SCFM70: "%.0f",
    SCFH70: "%.0f",
    "m3/h": "%.0f",
    "ft/min": "%.0f",
    K: "%.1f",
    C: "%.1f",
    "°C": "%.1f",
    c: "%.1f",
    F: "%.1f",
    R: "%.1f",
    bara: "%.3f",
    "bar(a)": "%.3f",
    barg: "%.3f",
    Pa: "%.0f",
    hPa: "%.0f",
    kPa: "%.1f",
    MPa: "%.4f",
    mbar: "%.0f",
    mbarg: "%.0f",
    mbara: "%.0f",
    psi: "%.2f",
    "kg/cm2": "%.3f",
    "lb/ft2": "%.0f",
    "lb/in2": "%.2f",
    rpm: "%.0f",
  },
};
